site_name: 'Documentation Template'
repo_url: https://github.com/harness-idp-sandbox/kai-java-rothschild-twelve
edit_uri: https://github.com/harness-idp-sandbox/kai-java-rothschild-twelve/blob/main/docs/index.md

nav:
  - Home: index.md

plugins:
  - techdocs-core